#!/usr/bin/env sh

# Installation script for Emacs-IDE

# Copyright (C) 2008-2011 Cédric Marie

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

printf "\033[1mCheck dependencies\033[0m\n"
printf "ctags: "
if which ctags > /dev/null ; then
  if ctags --version | grep -q Exuberant ; then
    printf "\033[1;32mOK\033[0m\n"
  else
    printf "\033[1;31mFAILED: your version of ctags is not \"Exuberant Ctags\"\033[0m\n"
    exit 1
  fi
else
  printf "\033[1;31mFAILED: ctags is not installed\033[0m\n"
  exit 1
fi
printf "cscope: "
if which cscope > /dev/null ; then
  printf "\033[1;32mOK\033[0m\n"
else
  printf "\033[1;31mFAILED: cscope is not installed\033[0m\n"
  exit 1
fi

printf "\n\033[1mRemove .elc files (if any)\033[0m\n"
rm -vf src/*.elc

printf "\n\033[1mCompile Emacs-IDE\033[0m\n"
emacs -nw -q -l compile-eide.el
# -nw: don't use X interface
# -q: don't load ~/.emacs
# -l file.el: load lisp file
compilation_ok=1
for file in `ls src/*.el`; do
  printf "${file}: "
  if [ -e ${file}c ]; then
    printf "\033[1;32mOK\033[0m\n"
  else
    printf "\033[1;31mFAILED\033[0m\n"
    compilation_ok=0
  fi
done
if [ $compilation_ok = 0 ]; then
  exit 1
fi

printf "\n\033[1mInstall Emacs-IDE\033[0m\n"
if [ -d /usr/local/share/emacs/site-lisp ]; then
  sudo cp -vf src/*.elc /usr/local/share/emacs/site-lisp/
elif [ -d /usr/share/emacs/site-lisp ]; then
  sudo cp -vf src/*.elc /usr/share/emacs/site-lisp/
else
  printf "\033[1;31mERROR: Neither /usr/local/share/emacs/site-lisp nor /usr/share/emacs/site-lisp exists\033[0m\n"
  exit 1
fi

printf "\n\033[1mRemove .elc files\033[0m\n"
rm -vf src/*.elc

printf "\n\033[1mEnable Emacs-IDE\033[0m\n"
if [ ! -e $HOME/.emacs ]; then
  printf "(require 'eide)\n" > $HOME/.emacs
  printf "(eide-start)\n" >> $HOME/.emacs
  printf "$HOME/.emacs did not exist, it has just been created with this content:\n"
  printf "\033[0;34m(require 'eide)\n"
  printf "(eide-start)\033[0m\n"
  printf "\033[0;32mEmacs-IDE is now automatically enabled when you launch Emacs\033[0m\n"
elif grep -q "(require 'eide)" $HOME/.emacs && grep -q "(eide-start)" $HOME/.emacs ; then
  printf "\033[0;32mEmacs-IDE is already enabled in $HOME/.emacs\033[0m\n"
else
  printf "\033[0;31mEmacs-IDE is not enabled in $HOME/.emacs\033[0m\n"
  printf "You must add these two lines in $HOME/.emacs:\n"
  printf "\033[0;34m(require 'eide)\n"
  printf "(eide-start)\033[0m\n"
fi
