(message ">>>>> Loading [ sh-mode ] Customization ....")
(defun my-shellscript-startup ()
  "Setup shell script mode."
  (interactive)
  (setq sh-basic-offset '8)
  (setq sh-indentation '8)
  (setq sh-indent-comment t)
  (setq indent-tabs-mode t)
  (setq sh-indent-for-case-label '0)
  (setq sh-indent-for-case-alt '+))
(add-hook 'sh-mode-hook 'my-shellscript-startup)
(add-hook 'sh-set-shell-hook 'flymake-shell-load)

;; sh-mode
(add-to-list 'auto-mode-alist '("/etc/profile"                  . sh-mode))
(add-to-list 'auto-mode-alist '("/etc/bash_completion"          . sh-mode))
(add-to-list 'auto-mode-alist '("\\.SH"                         . sh-mode))
(add-to-list 'auto-mode-alist '("\\.sh\\'"                      . sh-mode))
(add-to-list 'auto-mode-alist '("\\.bashrc"                     . sh-mode))
(add-to-list 'auto-mode-alist '("\\.csh\\'"                     . sh-mode))
(add-to-list 'auto-mode-alist '("\\.zsh\\'"                     . sh-mode))
(add-to-list 'auto-mode-alist '("\\rc\\'"                       . sh-mode))
(add-to-list 'auto-mode-alist '("\\.[ck]?sh\\'\\|\\.shar\\'\\|/\\.z?profile\\'" . sh-mode))
(add-to-list 'auto-mode-alist '("\\(/\\|\\`\\)\\.\\(bash_profile\\|z?login\\|bash_login\\|z?logout\\)\\'" . sh-mode))
(add-to-list 'auto-mode-alist '("\\(/\\|\\`\\)\\.\\(bash_logout\\|[kz]shrc\\|bashrc\\|t?cshrc\\|esrc\\)\\'" . sh-mode))
(add-to-list 'auto-mode-alist '("\\(/\\|\\`\\)\\.\\([kz]shenv\\|xinitrc\\|startxrc\\|xsession\\)\\'" . sh-mode))
(add-to-list 'auto-mode-alist '("\\.bash_history\\'"            . sh-mode))
(add-to-list 'auto-mode-alist '("\\.bash\\'"                    . sh-mode))
(add-to-list 'auto-mode-alist '("\\.bashrc.local\\'"            . sh-mode))